name       : kitinerary
version    : 18.12.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kitinerary-18.12.3.tar.xz : f45ef90cb3fb53d83a30837c304b9f7cfa5dbf2953421233d97c101d66a81f35
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - karchive-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
