name       : kitinerary
version    : 18.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kitinerary-18.08.3.tar.xz : 214e9acef6ec475c5bc1f13336eda40030cda312e77720220e4a2f429f2c60c2
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcalcore-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
