name       : kitinerary
version    : 18.08.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kitinerary-18.08.0.tar.xz : 14d89b35515d63a299ff054ca62d36b61c06e32b9ed12aed15d8fce4dda45c92
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcalcore-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
