name       : kitinerary
version    : 19.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kitinerary-19.04.3.tar.xz : c2e9d1ae70797968382538da98bc8f9555e0d8d13faeb739bdadb5844c989227
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - karchive-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
