name       : kitinerary
version    : 20.04.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kitinerary-20.04.1.tar.xz : ba3a61e482ce5a148b5b403198e7ad67704c8a6cc7ca4fce58ddef8c66f4b4cf
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - karchive-devel
    - kcalendarcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
