name       : kitinerary
version    : 18.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kitinerary-18.12.1.tar.xz : 9a6bf468bd0568f06dc81cd9c0408fd4fb788c47e61b2cff421100d949f47391
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - karchive-devel
    - kcalcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
