name       : kitinerary
version    : 21.08.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/kitinerary-21.08.0.tar.xz : 754e10ce09c929adfc75cce55988f19c6bfb9d211420db7236785ca10c45a241
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Quick)
    - karchive-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
