name       : kitinerary
version    : 21.08.1
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kitinerary-21.08.1.tar.xz : b1822bc6834c3965e343195d23a00d5ee486ce2e706e3d99762ec17734cbf564
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Quick)
    - karchive-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
