name       : kitinerary
version    : 21.04.1
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kitinerary-21.04.1.tar.xz : ef2f3b024e078060ecad137f57a45586b812b57de58200f90ed097d60a432785
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Quick)
    - karchive-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
