name       : kitinerary
version    : 21.08.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kitinerary-21.08.3.tar.xz : 6e7d052888b4e8f4b8b81a34917204c6d2326e10af1f56dcaf39d0f204c1d918
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Quick)
    - karchive-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
