name       : kitinerary
version    : 20.12.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kitinerary-20.12.2.tar.xz : 972b35fd40b6e6b88a4446da445b4293b7733d33d74a661b264435ca93f4327d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Data Model and Extraction System for Travel Reservation information
description: |
    A library containing itinerary data model and itinerary extraction code.
builddeps  :
    - pkgconfig(poppler)
    - pkgconfig(Qt5Quick)
    - karchive-devel
    - kcalendarcore-devel
    - kcontacts-devel
    - kmime-devel
    - kpkpass-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
